### ISSUE TITLE
Using `ByteVec` consuming trait methods on BString fails with "cannot move out of dereference of BString"

### ISSUE THREAD

**Issue by Byron** [BurntSushi/bstr#98] opened 2021-09-17 00:24 UTC
My actual goal is to convert a BString into a String, in a way that errors if it's not UTF-8. Basically `String::from_utf8(my_bstring.into_inner())`.

However, when trying it, I see 'cannot move out of dereference of `BString`', which makes sense as all functionality is implemented via `Deref`.

The problem is that my API uses `BStr` and sometimes `BString` so it would be desirable to be able dissolve the BString once again.

Here is [the playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=use%20bstr%3A%3AByteVec%3B%20%2F%2F%200.2.16%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20s%3A%20bstr%3A%3ABString%20%3D%20%22hello%22.into()%3B%0A%20%20%20%20s.into_string()%3B%0A%7D).

Thanks for your advice.

**Comment by BurntSushi** [comment] 2021-09-17 01:59
In terms of how to make progress here, I think you want `Vec::from(s).into_string()`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7492b80f15720c0b4585e9cc74d2359a

But this is probably a specific example of a general problem. Namely, that `BString` cannot call methods on `ByteVec`. I wonder how we might accomplish that. I can think of two ways:

1. Implement `ByteVec` for `BString` explicitly.
2. Add inherent methods on `BString` for all methods on `ByteVec` that move `self`.

I know (2) would work, but would be clunky/unfortunate. I'm less sure about (1), since I wonder how trait method resolution would work for methods that take `&self` or `&mut self`. But perhaps everything "just works" in that case.

**Comment by Byron** [comment] 2021-09-17 03:20
Thanks for the analysis and for showing a way forward.

> I know (2) would work, but would be clunky/unfortunate. I'm less sure about (1), since I wonder how trait method resolution would work for methods that take &self or &mut self. 

1) Seems like the most natural way even though it will require quite some repetition/call-forwarding. If there is ambiguity when `&self` and `&mut self` are involved, I wonder if it would even compile.

On the flip side, fixing this probably makes the API much more ergonomic, for instance, on `BString` something like `as_bstr()` won't work, but `as_ref()` does, which can be confusing to ~~some~~ me.

**Comment by BurntSushi** [comment] 2022-07-05 23:14
It turns out that this is a duplicate of #84. Similar ideas on how to move forward are discussed there.

To be honest, I'm still not quite sure what to do. If `impl ByteVec for BString` makes everything work, then that is definitely the easiest path. But someone has to try it out and see what, if any, failure modes it has.

Anyway, closing in favor of #84 since it was created first and also has a fair bit of context/info there.

**Closed by BurntSushi** 2022-07-05 23:14 UTC
