### ISSUE TITLE
Add parsing related functions and traits.

### ISSUE THREAD

**Issue by MashPlant** [BurntSushi/bstr#65] opened 2020-06-22 10:43 UTC
In the `str` type, we have: 

```rust
pub fn parse<F>(&self) -> Result<F, <F as FromStr>::Err>
where
    F: FromStr, 
```

Sometimes I just want to parse a `u32` from a byte slice, but currently when working with std lib, I can only first perform checked convert from `& [u8]` it to `& str`, and then call `str::parse`. It would be a performance loss, because I don't really care whether this byte slice is a valid UTF-8 string.

Is it possible to add similiar functions and traits in `bstr`?

**Comment by BurntSushi** [comment] 2020-06-22 11:50
This appears to be a duplicate of https://github.com/BurntSushi/bstr/issues/64, which was created just a few hours before this one.

**Closed by BurntSushi** 2020-06-22 11:50 UTC
