### ISSUE TITLE
Goals of this crate

### ISSUE THREAD

**Issue by m-ou-se** [BurntSushi/bstr#25] opened 2019-10-16 10:19 UTC
(Continuation from https://twitter.com/burntsushi5/status/1182677304478175232)

---

I was wondering what the (implementation) goals of this crate are. I noticed this crate implements pretty much all UTF-8 algorithms itself, even those that `core` already exposes, such as [`from_utf8`](https://doc.rust-lang.org/beta/std/str/fn.from_utf8.html). And even quite a few of the other algorithms are still implemented in `core`, although they are not exposed (as stable) (e.g. [`Utf8Lossy`](https://doc.rust-lang.org/core/str/lossy/struct.Utf8Lossy.html)).

So a few questions:

- Why are things like `from_ut8` re-implemented (as the [`validate`](https://github.com/BurntSushi/bstr/blob/083d609e16fe9c850b2e08708c0d2ecb191d44d1/src/utf8.rs#L331) function)? Is this implementation better, and if so, is the goal to merge this into `core` at some point? Or are the goals of `core::str::from_utf8` and `validate` in this crate different in some way (e.g. optimizing for something different)?

- Should we try (through an RFC) to get some of the `str_internals` of `core` exposed, because apparently they are useful outside of `core`, such as [`next_code_point`](https://doc.rust-lang.org/core/str/fn.next_code_point.html)? If they ever do get stabilized, should the bstr crate use that one instead of keeping [its own implementation](https://github.com/BurntSushi/bstr/blob/083d609e16fe9c850b2e08708c0d2ecb191d44d1/src/utf8.rs#L473)?

- Should there be some feature that can be enabled/disabled to turn this crate into a more minimal 'just small wrappers around core' type of crate? Right now, I would avoid using bstr in embedded projects, because&mdash;even when only using `BStr`s `Display` or something&mdash;it adds tables/functions that are more or less duplicates of things that are often also pulled in though `core`, which can be quite a waste of space (which is scarce on embedded platforms).

The reason I'm asking these questions is that I want to contribute a bit to this crate to make it more useful for a few applications I'm using it for, but I'm not sure what direction this crate should grow in.

---

In any case, thanks for making this crate. It's very nice! ^^

**Comment by BurntSushi** [comment] 2019-10-18 16:57
Hiya! Thanks for reaching out. I appreciate the questions.

> Why are things like from_ut8 re-implemented (as the validate function)?

There are a few reasons:

Firstly, bstr really wants its own UTF-8 decoder because the APIs exposed
by std aren't really in the right "shape" for what bstr wants to do. In
particular, bstr wants to provide things like the
[`Chars`](https://docs.rs/bstr/0.2.8/bstr/struct.Chars.html)
iterator, which is analogous to std's `Chars` iterator, except it automatically
converts invalid UTF-8 sequences into the Unicode replacement codepoint.
Actually implementing this iterator using only APIs from std is tricky, but
possible. The docs for
[`std::str::from_utf8`](https://doc.rust-lang.org/std/str/fn.from_utf8.html)
and
[`std::str::Utf8Error`](https://doc.rust-lang.org/std/str/struct.Utf8Error.html)
even have some relevant examples. The problem is that a `Chars` iterator wants
to process the input in a codepoint-by-codepoint fashion, where as `from_utf8`
wants a big chunk all at once. It is possible to work-around this in a fairly
unnatural way by examining the size of the next codepoint, and sub-slicing it
(up to 4 bytes), and then feed that to `from_utf8`. You can see an example of
that
[here](https://github.com/BurntSushi/globset/blob/9aa90cb2dcbe59d4e6770a747b48645418aa4a3d/src/utf8.rs#L13-L45).
This is almost certainly going to add performance overhead, and moreover, makes
it quite tricky to implement
[substitution of maximal subparts](https://docs.rs/bstr/0.2.8/bstr/#handling-of-invalid-utf-8)
as a way of handling invalid UTF-8 data.

Secondly, building off the first reason, bstr specifically makes its handling
of invalid UTF-8 an API guarantee. std does not, although I suspect it would be
difficult to get away with breaking it. (Incidentally, both std and bstr handle
invalid UTF-8 in the same way.)

Ideally, if std/core exposed a function like
[`bstr::decode_utf8`](https://docs.rs/bstr/0.2.8/bstr/fn.decode_utf8.html),
then bstr wouldn't need to roll its own UTF-8 decoder internally. It could
still re-implement `from_utf8` (for performance reasons), but at least it
wouldn't need to re-implement all of UTF-8 decoding. AFAIK, there is no
appetite for a function like this in std. I've asked many moons ago.

Thirdly, yes, bstr's implementation _is_ faster in many cases. Whether it is
faster in all cases is not clear, as benchmarking this sort of thing is hard
and just haven't had the time to do it exhaustively. (There are benchmarks for
it though.) In particular, one of its main optimizations is by using SIMD to
quickly skip through ASCII portions of text. That means that in the
exceptionally common case of ASCII on `x86_64` processors, UTF-8 validation is
going to be quite a bit faster than what's in std.

> Is this implementation better, and if so, is the goal to merge this into core
> at some point? Or are the goals of core::str::from_utf8 and validate in this
> crate different in some way (e.g. optimizing for something different)?

I think the primary reason for its existence is the aforementioned API
differences. Even if we squared those away, the performance reason remains. In
theory, std could use the same implementation, however I think it would be a
bit precarious since the _actual_ implementation lives in `core`. AFAIK, `core`
is not yet set up in a way that permits it to use explicit SIMD. It's not clear
if it ever will be. There have been discussions about that---perhaps on the
`packed_simd` or `stdarch` repos---but I don't have any links off-hand.

> Should we try (through an RFC) to get some of the str_internals of core
> exposed, because apparently they are useful outside of core, such as
> next_code_point? If they ever do get stabilized, should the bstr crate use
> that one instead of keeping its own implementation?

I personally do not have the bandwidth to write an RFC. IMO, bstr is basically
the first step in that process anyway. To a certain extent, such an RFC should
have some convincing evidence that the exposure of said APIs are useful to a
good number of people. Personally, I think they _probably_ are, but even I am
not quite convinced yet. I work in a particular domain where these routines are
incredibly useful, but it's not clear to me how widely applicable they are. On
top of that, even if they were useful to a lot of folks, one would likely also
need to craft a compelling reason as to why putting them in a crate (like bstr)
isn't sufficient, and why `core` (or `std`) needs to expose them.

It kind of sounds like you might be in the sweet spot where you'd rather bstr
defer its internal implementation to `core` to minimize binary size, so I
imagine your use case would be a motivating factor. I'm not sure how strong it
is. We're likely talking about a pretty small portion of code here.

As for whether `bstr` would use `next_code_point` or not, I'm not sure. Quite
possibly. It would almost certainly need some tweaking in its API. To be
honest, I'd much rather bstr's `decode_utf8`. (One particular sticking point is
that `next_code_point` returns a `u32`, and it's not clear what kind of things
the caller is permitted to assume about that value.)

> Should there be some feature that can be enabled/disabled to turn this crate
> into a more minimal 'just small wrappers around core' type of crate? Right
> now, I would avoid using bstr in embedded projects, because—even when only
> using BStrs Display or something—it adds tables/functions that are more or
> less duplicates of things that are often also pulled in though core, which
> can be quite a waste of space (which is scarce on embedded platforms).

Is it possible for you to quantify this? You can already disable a number of
Unicode APIs and such. The UTF-8 tables are probably negligible. Otherwise,
this crate pretty much _is_ just a thin wrapper around things in core/std,
_except_ for the things that aren't exposed. One of those is UTF-8 decoding,
as you brought up, but another significant one is substring search. `core`
implements a very similar algorithm, but only provides searching APIs for
`str`. If `core` provide substring search on `&[u8]`, then it's conceivable
that `bstr` could grow a feature to use `core`'s algorithm. But my variant has
some clever frequency based acceleration additions to it, that I'd almost
certainly want to keep, and may be difficult to get accepted into `core`.

**Comment by BurntSushi** [comment] 2020-01-10 18:00
I'm going to close this issue for now. If there are any more questions, feel free to ask!

**Closed by BurntSushi** 2020-01-10 18:00 UTC
